### PR TITLE
Test newer Ruby versions

### PR DESCRIPTION
**Pull request by mrcasals**
This PR tests spinach against the newest Ruby versions.

### CODE REVIEW

**Comment by mrcasals** [comment]
@ywen hi! Would you mind reviewing this PR, please? It tests spinach against the newest Ruby versions, and drops supports for EOL versions.

Thank you!

**Comment by ywen** [comment]
It shows this?

Screen Shot 2020-04-03 at 12 57 54 PM

**Comment by mrcasals** [comment]
@ywen this PR also ports the tests from TravisCI to GitHub Actions, to try it out. I can bring that back if you want me to, but so far I'm pretty happy with GitHub Actions. TravisCI took a while to start the jobs, for some reason, that's why I switched!

**Comment by ywen** [comment]
> @ywen this PR also ports the tests from TravisCI to GitHub Actions, to try it out. I can bring that back if you want me to, but so far I'm pretty happy with GitHub Actions. TravisCI took a while to start the jobs, for some reason, that's why I switched!

No I think github action seems nice. Please get rid of travisCI hook. Thank you!

**Comment by mrcasals** [comment]
@ywen done!

**Pull request merged**
