### PR TITLE
Minor release for run randomization feature

### PR DESCRIPTION
**Pull request by yarmiganosca**
As mentioned in #196, here's a version bump PR. I'm not sure if any other tasks need doing before a release, but if you tell me what they are, I'll be happy to do them!

### CODE REVIEW

**Comment by yarmiganosca** [comment]
I still have no idea what's wrong with the Travis runs for JRuby.

**Comment by ywen** [comment]
I am happy to look into jRuby failure tonight or sometime tomorrow

**Comment by ywen** [comment]
@yarmiganosca It appears that `simplecov` isn't working well with jRuby. Maybe you can consider doing the as suggested in https://stackoverflow.com/a/45873770/198616 to get more detailed info on why?

**Comment by ywen** [comment]
Under jruby 9.1.2 I can run `bundle exec rake` locally with an exit 1 as well. So I can debug locally. Will do so when I am free next week

**Comment by ywen** [comment]
lol. oh wow nice finding! Yeah I agree we can update ruby version

**Pull request closed without merging**
