### PR TITLE
Add a --audit flag for finding missing/unused steps

### PR DESCRIPTION
**Pull request by pedantic-git**
`spinach --generate` is awesome if you get your feature files right first time, but I often find that over time features change and I have to add to or edit old feature files.

This tool helps with that. Running `spinach --audit` will do an audit of all the feature files and their shared modules.

If steps are missing, it will generate all the pending step definitions that need adding somewhere and output them to stdout.

If steps are unused, it will print out the filename and line number of the unused step so it can be removed. [**Note**: In order to do this, a slight change has been made to Spinach::DSL to have it keep track of steps as they're defined. I hope this is OK/useful!]

(The audit can also be run on individual feature files, but of course it may detect shared steps as being unused when they are in fact being used by other features! It doesn't do this when run over the whole directory.)

I have tried to keep to the coding style as much as possible and I've added a lot of scenarios to defend all the possible quirks I could think of.

Please let me know if you'd like any changes making and I hope you find this useful!

### CODE REVIEW

**Comment by pedantic-git** [comment]
Looks like CI is passing but I have some Hound issues -  let me take care of those.

**Comment by pedantic-git** [comment]
I've taken care of the hound issues in most of the `lib` code, but I can't get the complexity of the `audit_file` method down any further without breaking the Auditor down into smaller classes. Let me know if you need me to do this.

I've ignored the issues reported on the step files because I'm assuming you don't have the same code review standards on those?

**Comment by josepjaume** [comment]
Hi, thanks so much for your Pull Request! This is a really, really nice feature and you certainly put a lot of effort on it.

I'm 👍 on this - do you think you could update the `Readme.md` explaining how to use the feature?

We'll release a new version after merging. Thanks ❤️

**Comment by josepjaume** [comment]
Oh, and sorry for all Hound CI's trolling :(. It looks like we mistakenly activated it for this repo and, without further configuration, it's quite annoying - we usually don't follow some of his hints. Sorry you had to deal with it, but hopefully gave some useful advice!

**Comment by pedantic-git** [comment]
Hi @josepjaume - thanks for saying so! The feature has already saved me tons of time even though I only implemented it last week so I hope it will be useful for you and other users too!

I've added those instructions to the README as requested. Let me know if I can help with anything else!

**Pull request merged**
