### PR TITLE
Don't redirect stdout before calling Capybara's `visit` method

### PR DESCRIPTION
**Pull request by kylesmile**
Redirecting stdout breaks using a debugging tool like `pry` from a controller action. Here's a [small example](https://github.com/kylesmile/spinach_pry_bug).

I'm not sure if there's a good way to write a test for this, but suggestions are welcome.

### CODE REVIEW

**Comment by oriolgual** [comment]
This was introduced here https://github.com/codegram/spinach/commit/9c08137c4ea9e70c79e219e2345e9df8ac042870#diff-ab028e449b86b3d40a35a0dc65a6a90a, @josepjaume do you remember why?

**Comment by mrcasals** [comment]
Found this bug myself a couple of times too, actually :/

**Comment by wzcolon** [comment]
For others, until this gets merged...

```ruby
# config/initializers/spinach.rb
if Rails.env.test?
    require 'spinach/capybara'

    module Spinach
      class FeatureSteps
        module Capybara
          def visit(*args)
            capybara_visit *args
          end
        end
      end
    end
  end
```

**Comment by alkuzad** [comment]
:+1: what is the reason for redirection ? Does capybara prints anything ?

**Comment by kylesmile** [comment]
Capybara doesn't seem to print anything that I've seen. I'm wondering if Capybara was noisier when that redirection was added.

**Pull request merged**
